version: '3.9'
services:
    client-react:
      ports:
        - 5173:5173
      networks:
        - backend
        - frontend
      image: mohamedsafy/client-react:0
      build:
        context: client-react
        dockerfile: dockerfile
      volumes:
        - ./client-react/vite.config.js:/usr/src/app/vite.config.js

    api-node:
      environment:
        - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
      image: mohamedsafy/api-node:0
      build:
        context: api-node
        dockerfile: dockerfile
      networks:
        - backend
      depends_on:
        - db

    db:
      environment:
        - POSTGRES_PASSWORD=foobarbaz
      image: postgres
      networks:
        - backend


networks:
  frontend:
  backend: