version: '3.9'
services:
    client-react:
      ports:
        - 80:8080
      networks:
        - backend
        - frontend
      image: client-react:0
      build:
        context: client-react
        dockerfile: dockerfile
      volumes:
        - ./client-react/vite.config.js:/usr/src/app/vite.config.js
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost"]
        interval: 10s
        timeout: 5s
        retries: 3
        disable: true

    api-node:
      environment:
        - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
      image: api-node:0
      build:
        context: api-node
        dockerfile: dockerfile
      networks:
        - backend
      depends_on:
        - db
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
        interval: 10s
        timeout: 5s
        retries: 3
        disable: true

    db:
      environment:
        - POSTGRES_PASSWORD=foobarbaz
      image: postgres
      networks:
        - backend
      healthcheck:
        test: ["CMD", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 10s
        disable: true


networks:
  frontend:
  backend: