FROM node:24-alpine3.21 AS build

WORKDIR /usr/src/app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

###

FROM nginxinc/nginx-unprivileged:alpine3.22-perl

COPY  ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build usr/src/app/dist/ /usr/share/nginx/html

EXPOSE 8080