name: Hello World Workflow

on: workflow_dispatch

jobs:
    hello-world-job:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "Hello from the echo step inside hello world job!"  
    